worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # DevSecOps: Security Headers
    server_tokens off; # Nginx ka version hide karne ke liye (Hackers se bachne ke liye)
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Upstreams (Apne internal containers ka pata)
    upstream identity_backend {
        server identity-service:8080;
    }

    server {
        listen 80;
        server_name localhost;

        # 1. Auth Service Routes (Login/Register yahan jayenge)
        location /api/auth/ {
            # URL rewrite: /api/auth/login -> /login
            rewrite ^/api/auth/(.*) /$1 break; 
            proxy_pass http://identity_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/convert {
            proxy_pass http://identity_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # Authorization header (Bearer token) ko aage pass karne ke liye
            proxy_pass_header Authorization;
        }

        # Health Check Route
        location /health {
            return 200 '{"status":"Gateway is Healthy and Secure"}';
            default_type application/json;
        }
    }
}