apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: devsecops-secure-nginx-platform
  namespace: devsecops-secure-nginx
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: devsecops-secure-nginx-platform
