apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-nginx-sa
  namespace: devsecops-secure-nginx
  labels:
    app.kubernetes.io/name: devsecops-secure-nginx-platform
automountServiceAccountToken: false
