apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secure-nginx-role
  namespace: devsecops-secure-nginx
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["secure-nginx-config"]
    verbs: ["get"]
