apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secure-nginx-rolebinding
  namespace: devsecops-secure-nginx
subjects:
  - kind: ServiceAccount
    name: secure-nginx-sa
    namespace: devsecops-secure-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secure-nginx-role
